### ISSUE TITLE
[Front-End] - Add Github Link

### ISSUE THREAD

**Issue by michmich112** [michmich112/gh-action-stats#27]
## User Story
As a Visitor or User,
I would like to access the Github Repository (https://github.com/michmich112/gh-action-stats) from the landing page and the GetStarted Page.
So that I can see the code for myself and possibly contribute.

## Requirements
The user should be able to access the repo from a github icon at the footer of the landing page and the Get Stated page.
This link should open in a new tab.

**Comment by yashfalke77** [comment]
@michmich112  can I work on this issue?

**Comment by michmich112** [comment]
Hi @yashfalke77!
Sure! I've invited you as a contributor to the project :)
Please make sure to read over the quick contribution guide for your reference: [https://github.com/michmich112/gh-action-stats/wiki/Contribution-Guide](https://github.com/michmich112/gh-action-stats/wiki/Contribution-Guide)
Feel free to join the discord as well!

**Comment by yashfalke77** [comment]
hey @michmich112  I had completed this task and requested the pull request do check out and if any improvement needed do tag me :)

**Comment by michmich112** [comment]
Thanks @yashfalke77! Tagged you for some clarifications
