### ISSUE TITLE
[Front-End] - Add Discord link

### ISSUE THREAD

**Issue by michmich112** [michmich112/gh-action-stats#28]
## User Story
As a visitor or user
I would like access the community Discord from the landing page and the get started page
So i can communicate with the team and stay up to date with improvements

## Requirements
The Discord should be accessible through a discord icon at the footers of the landing page and the get started page

## Support
Discord invitation link: [https://discord.gg/EHtUEecDn3](https://discord.gg/EHtUEecDn3)

**Comment by yashfalke77** [comment]
@michmich112 I would like to work on this issue
