### ISSUE TITLE
[Configuration] - Setup Prettier/TSLint for unified formatting.

### ISSUE THREAD

**Issue by michmich112** [michmich112/gh-action-stats#37]
Set up ODE Formatter for Typescript which will work for svelte.js, sveltekit and typescript.
Additionally, setup tsLint file so linting is consistent between systems.

**Comment by usmt-cop** [comment]
Great
I will be implementing all this from scratch 🤠
It might take a little longer thoug

**Comment by michmich112** [comment]
All good :)
You got this 💪🏼
